## ---------------------------
## Script name: DuplicateContacts.R
##
## Purpose of script: To combine the different sources of contact information 
##    for the eMOLT project and remove duplicates before loading the contact
##    table into the MySQL database
##
## Date Created: 2022-03-18
##
## Copyright (c) NOAA Fisheries, 2022
##
## Email: george.maynard@noaa.gov
##
## ---------------------------
## Notes: requires the .csv files generated by TelemetryStatus_2_Contacts.R and
##    OldOracle_2_MySQL.R (Contacts_pt1.csv and Contacts_pt2.csv)   
##
library(dplyr)
## ---------------------------
## Read in the files
pt1=read.csv("C:/Users/george.maynard/Documents/eMOLT-db/Uploads/Independent_Tables/Contacts_pt1.csv")
pt2=read.csv("C:/Users/george.maynard/Documents/eMOLT-db/Uploads/Independent_Tables/Contacts_pt2.csv")
## Create an ID column in each file that is just the first name and last name
##    combined without any spaces
pt1$ID=gsub(
  " ",
  "",
  paste0(pt1$FIRST_NAME,pt1$LAST_NAME)
)
pt2$ID=gsub(
  " ",
  "",
  paste0(pt2$FIRST_NAME,pt2$LAST_NAME)
)
## If the ID exists in both tables, remove it from the older table and update 
##    the newer table to be as complete as possible
for(i in 1:nrow(pt2)){
  if(pt2$ID[i]%in%pt1$ID){
    pt2$PHONE[i]=ifelse(
      pt2$PHONE[i]=="",
      pt1$PHONE[which(pt1$ID==pt2$ID[i])],
      pt2$PHONE[i]
      )
    pt2$EMAIL[i]=ifelse(
      pt2$EMAIL[i]=="",
      pt1$EMAIL[which(pt1$ID==pt2$ID[i])],
      pt2$EMAIL[i]
    )
    pt2$STREET_1[i]=ifelse(
      pt2$STREET_1[i]=="",
      pt1$STREET_1[which(pt1$ID==pt2$ID[i])],
      pt2$STREET_1[i]
    )
    pt2$CITY[i]=ifelse(
      pt2$CITY[i]=="",
      pt1$CITY[which(pt1$ID==pt2$ID[i])],
      pt2$CITY[i]
    )
    pt2$STATE_POSTAL[i]=ifelse(
      pt2$STATE_POSTAL[i]=="",
      pt1$STATE_POSTAL[which(pt1$ID==pt2$ID[i])],
      pt2$STATE_POSTAL[i]
    )
    pt2$ZIP[i]=ifelse(
      pt2$ZIP[i]=="",
      pt1$ZIP[which(pt1$ID==pt2$ID[i])],
      pt2$ZIP[i]
    )
    ## Remove the duplicate contact from the older sheet
    pt1=pt1[-which(pt1$ID==pt2$ID[i]),]
  }
}
## Merge the two data sets
CONTACTS=rbind(pt1,pt2)
## Remove the now unecessary ID column
CONTACTS$ID=NULL
## Add a new empty column to facilitate upload to the database
CONTACTS$CONTACT_ID=0
## Clear out any remaining problems in the telephone number column
CONTACTS$PHONE=gsub(
  " ",
  "",
  CONTACTS$PHONE
)
CONTACTS$PHONE=gsub(
  "\\.",
  "",
  CONTACTS$PHONE
)
CONTACTS$PHONE=gsub(
  "=",
  "",
  CONTACTS$PHONE
)
## Reorder columns to match database format
col_order=c(
  'CONTACT_ID',
  'FIRST_NAME',
  'LAST_NAME',
  'PHONE',
  'EMAIL',
  'PREFERRED_CONTACT',
  'STREET_1',
  'STREET_2',
  'CITY',
  'STATE_POSTAL',
  'ZIP',
  'ROLE'
)
CONTACTS=CONTACTS[,col_order]
## Set empty columns to blank
CONTACTS$PREFERRED_CONTACT=ifelse(
  is.na(CONTACTS$PREFERRED_CONTACT),
  "",
  CONTACTS$PREFERRED_CONTACT
)
CONTACTS$STREET_2=ifelse(
  is.na(CONTACTS$STREET_2),
  "",
  CONTACTS$STREET_2
)
CONTACTS$ROLE=ifelse(
  is.na(CONTACTS$ROLE),
  "",
  CONTACTS$ROLE
)
CONTACTS$ROLE=ifelse(
  CONTACTS$ROLE=='RETIRED',
  'INACTIVE',
  CONTACTS$ROLE
)

## Export the table to a .csv file
write.csv(
  CONTACTS,
  "C:/Users/george.maynard/Documents/eMOLT-db/Uploads/Independent_Tables/Contacts.csv",
  row.names=FALSE
)

# ## Print a list of duplicate values
# select(
#   subset(
#     pt1,
#     pt1$ID%in%pt2$ID
#   ),
#   FIRST_NAME,
#   LAST_NAME
# )
# duplicates1=subset(
#   pt1,
#   pt1$ID%in%pt2$ID
# )
# duplicates1=duplicates1[order(duplicates1$LAST_NAME),]
# duplicates2=subset(
#   pt2,
#   pt2$ID%in%pt1$ID
# )
# duplicates2=duplicates2[order(duplicates2$LAST_NAME),]
# ## Check to see if information matches exactly
# for(i in 1:nrow(duplicates1)){
#   print(paste(duplicates1$FIRST_NAME[i],duplicates1$LAST_NAME[i],sep=" "))
#   if(duplicates1[i,3]!=duplicates2[i,3]){
#     print(c(duplicates1[i,3],duplicates2[i,3]))
#   }
#   if(duplicates1[i,4]!=duplicates2[i,4]){
#     print(c(duplicates1[i,4],duplicates2[i,4]))
#   }
#   if(duplicates1[i,6]!=duplicates2[i,6]){
#     print(c(duplicates1[i,6],duplicates2[i,6]))
#   }
#   if(duplicates1[i,8]!=duplicates2[i,8]){
#     print(c(duplicates1[i,8],duplicates2[i,8]))
#   }
#   print("----------")
# }
