## ---------------------------
## Script name: DuplicateContacts.R
##
## Purpose of script: To combine the different sources of contact information 
##    for the eMOLT project and remove duplicates before loading the contact
##    table into the MySQL database
##
## Date Created: 2022-03-18
##
## Copyright (c) NOAA Fisheries, 2022
##
## Email: george.maynard@noaa.gov
##
## ---------------------------
## Notes: requires the .csv files generated by TelemetryStatus_2_Contacts.R and
##    OldOracle_2_MySQL.R (Contacts_pt1.csv and Contacts_pt2.csv)   
##
library(dplyr)
## ---------------------------
## Read in the files
pt1=read.csv("C:/Users/george.maynard/Documents/eMOLT-db/Uploads/Independent_Tables/Contacts_pt1.csv")
pt2=read.csv("C:/Users/george.maynard/Documents/eMOLT-db/Uploads/Independent_Tables/Contacts_pt2.csv")
## Create an ID column in each file that is just the first name and last name
##    combined without any spaces
pt1$ID=gsub(
  " ",
  "",
  paste0(pt1$FIRST_NAME,pt1$LAST_NAME)
)
pt2$ID=gsub(
  " ",
  "",
  paste0(pt2$FIRST_NAME,pt2$LAST_NAME)
)
## Print a list of duplicate values
select(
  subset(
    pt1,
    pt1$ID%in%pt2$ID
  ),
  FIRST_NAME,
  LAST_NAME
)
duplicates1=subset(
  pt1,
  pt1$ID%in%pt2$ID
)
duplicates1=subset(
  pt2,
  pt2$ID%in%pt1$ID
)