CREATE OR REPLACE VIEW VESSEL_VISIT_VIEW AS
  SELECT
    VESSEL_VISIT_LOG.VISIT_DATE,
    CONTACTS.FIRST_NAME AS TECH_FIRST,
    CONTACTS.LAST_NAME AS TECH_LAST,
    VESSELS.VESSEL_NAME,
    PORTS.PORT_NAME,
    VESSEL_VISIT_LOG.VISIT_NOTES
  FROM
    VESSEL_VISIT_LOG
    INNER JOIN VESSELS 
      ON VESSEL_VISIT_LOG.VESSEL_ID = VESSELS.VESSEL_ID
    INNER JOIN CONTACTS
      ON VESSEL_VISIT_LOG.LEAD_TECH = CONTACTS.CONTACT_ID
    INNER JOIN PORTS
      ON VESSEL_VISIT_LOG.PORT = PORTS.PORT
;