CREATE OR REPLACE VIEW VESSEL_MAC AS
SELECT 
  HARDWARE_ADDRESSES.HARDWARE_ADDRESS,
  EQUIPMENT_INVENTORY.EQUIPMENT_TYPE,
  EQUIPMENT_INVENTORY.MAKE,
  EQUIPMENT_INVENTORY.MODEL, 
  VESSEL_VISIT_LOG.VISIT_DATE, 
  VESSELS.VESSEL_NAME
FROM 
  HARDWARE_ADDRESSES
  INNER JOIN EQUIPMENT_CHANGE
    ON HARDWARE_ADDRESSES.INVENTORY_ID = EQUIPMENT_CHANGE.END_INVENTORY_ID
  INNER JOIN EQUIPMENT_INVENTORY
    ON EQUIPMENT_CHANGE.END_INVENTORY_ID = EQUIPMENT_INVENTORY.INVENTORY_ID
  INNER JOIN VESSEL_VISIT_LOG
    ON EQUIPMENT_CHANGE.VISIT_ID = VESSEL_VISIT_LOG.VISIT_ID
  INNER JOIN VESSELS
    ON VESSEL_VISIT_LOG.VESSEL_ID = VESSELS.VESSEL_ID
WHERE 
  ADDRESS_TYPE = 'MAC';
  