SELECT 
inventory.SERIAL_NUMBER,
inventory.MAKE,
inventory.MODEL,
inventory.FIRMWARE_VERSION,
inventory.CALIBRATION_DATE,
inventory.MAC_ADDRESS,
battery_change.EQUIPMENT_MAINTENANCE_DATE AS BATTERY_CHANGE
FROM
EQUIPMENT_INVENTORY AS inventory
LEFT JOIN
(SELECT * FROM EQUIPMENT_MAINTENANCE WHERE EQUIPMENT_MAINTENANCE_EVENT_PK = 3) AS battery_change
ON inventory.INVENTORY_PK = battery_change.EQUIPMENT_INVENTORY_PK
WHERE inventory.EQUIPMENT_TYPE_PK = 1 AND inventory.MODEL != "MATP-2W" AND inventory.EQUIPMENT_LOCATION_PK NOT IN (5,6)